export const mockProject = {
  title: "title",
  category: "category",
  tools: [],
  mainTag: [],
  image: "image.png",
  excerpt: "some excerpt",
  fullDescription: "some description",
  projectUrl: undefined,
  github: "https://github.com",
};

export const mockProjectListLong = [
  {
    title: "title1",
    category: "category",
    tools: ["Next"],
    mainTag: [],
    image: "image.png",
    excerpt: "some excerpt",
    fullDescription: "some description",
    projectUrl: undefined,
    github: "https://github.com",
  },
  {
    title: "title2",
    category: "category",
    tools: [],
    mainTag: [],
    image: "image.png",
    excerpt: "some excerpt",
    fullDescription: "some description",
    projectUrl: undefined,
    github: "https://github.com",
  },
  {
    title: "title3",
    category: "category",
    tools: [],
    mainTag: [],
    image: "image.png",
    excerpt: "some excerpt",
    fullDescription: "some description",
    projectUrl: undefined,
    github: "https://github.com",
  },
  {
    title: "title4",
    category: "category",
    tools: [],
    mainTag: [],
    image: "image.png",
    excerpt: "some excerpt",
    fullDescription: "some description",
    projectUrl: undefined,
    github: "https://github.com",
  },
  {
    title: "title5",
    category: "category",
    tools: [],
    mainTag: [],
    image: "image.png",
    excerpt: "some excerpt",
    fullDescription: "some description",
    projectUrl: undefined,
    github: "https://github.com",
  },
  {
    title: "title6",
    category: "category",
    tools: [],
    mainTag: [],
    image: "image.png",
    excerpt: "some excerpt",
    fullDescription: "some description",
    projectUrl: undefined,
    github: "https://github.com",
  },
  {
    title: "title7",
    category: "category",
    tools: [],
    mainTag: [],
    image: "image.png",
    excerpt: "some excerpt",
    fullDescription: "some description",
    projectUrl: undefined,
    github: "https://github.com",
  },
  {
    title: "title8",
    category: "category",
    tools: [],
    mainTag: [],
    image: "image.png",
    excerpt: "some excerpt",
    fullDescription: "some description",
    projectUrl: undefined,
    github: "https://github.com",
  },

  {
    title: "title9",
    category: "category",
    tools: [],
    mainTag: [],
    image: "image.png",
    excerpt: "some excerpt",
    fullDescription: "some description",
    projectUrl: undefined,
    github: "https://github.com",
  },
  {
    title: "title10",
    category: "category",
    tools: [],
    mainTag: [],
    image: "image.png",
    excerpt: "some excerpt",
    fullDescription: "some description",
    projectUrl: undefined,
    github: "https://github.com",
  },
  {
    title: "title11",
    category: "category",
    tools: [],
    mainTag: [],
    image: "image.png",
    excerpt: "some excerpt",
    fullDescription: "some description",
    projectUrl: undefined,
    github: "https://github.com",
  },
];
